version: 2

terraform: &terraform
  docker:
    - image: hashicorp/terraform:0.11.13
  working_directory: /tmp/workspace/terraform

notify:
  webhooks:
    - url: https://outlook.office.com/webhook/f56ae5c1-eecf-43ad-83c1-bb0d73bd13b5@5e0b361b-59ed-466e-8759-030448046197/CircleCI/b38cbeb3699648389914128950826ddc/3ead529e-38c0-45d8-b1d5-2126df5677b0

jobs:
  validate:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init -input=false
      - run:
          name: Validate Terraform configurations
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (terraform validate -check-variables=false "$m" && echo "√ $m") || exit 1 ; done
      - run:
          name: Check if Terraform configurations are properly formatted
          command: if [[ -n "$(terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
      - run:
          name: Install tflint
          command: curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.4.2/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
      - run:
          name: Check Terraform configurations with tflint
          command: tflint
          command: terraform get
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init -input=false
      - run:
          name: terraform apply
          command: terraform apply -input=false -auto-approve
        - run: 
          name: terraform destroy
          command: terraform destroy
      - persist_to_workspace:
          root: .
          paths: .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate:
          context: datacenternetwork-general-sandbox
      - build:
          context: datacenternetwork-general-sandbox
          filters:
            branches:
              only: master
          requires:
            - validate